language: go
sudo: false
matrix:
  include:
    - go: 1.x
      env: LATEST=true
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x
    - go: tip
  allow_failures:
    - go: tip

before_install:
  - go get -t -v ./...
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci


after_success:
  on:
    branch: master
    - export GIT_COMMIT=$(git rev-list -1 HEAD)
    - export GIT_TAG=$(git describe --tags)
    - gox -osarch="windows/amd64 darwin/amd64 linux/amd64 linux/arm" -output "dist/hussar_{{.OS}}-{{.Arch}}" -ldflags "-X main.GitCommit=$GIT_COMMIT" -ldflags "-X main.VersionString=$GIT_TAG"
    - ghr --username kscarlett --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
